[tool.black]
line-length = 79
target-version = ['py36', 'py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.tox
    | \*.egg-info
    | _build
    | build
    | dist
    | migrations
  )/
)
'''

[build-system]
requires = ["setuptools", "wheel"]
